run:
  timeout: 5m
  tests: true
linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
      - name: blank-imports
        disabled: true
linters:
  enable:
    - govet
    - staticcheck
    - revive
    - ineffassign
    - errcheck
    - gosimple
    - bodyclose
    - sqlclosecheck
    - gocritic
issues:
  exclude-use-default: false
